class BaseConfig(object):
    DEBUG = False
    TESTING = False
    LOGGER_NAME = 'mass_server_flask'
    BOOTSTRAP_SERVE_LOCAL = True
    BOOTSTRAP_USE_MINIFIED = True
    SCHEDULER_VIEWS_ENABLED = False
    OBJECTS_PER_PAGE = 100
    SCHEDULE_ANALYSES_INTERVAL = 30
    MAX_SCHEDULE_THRESHOLD = 100
